"""initial schema

Revision ID: a19875f15fe2
Revises:
Create Date: 2026-03-07

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a19875f15fe2'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stores',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('brand', sa.String(length=100), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('state', sa.String(length=2), nullable=False),
    sa.Column('timezone', sa.String(length=50), nullable=False),
    sa.Column('meeting_cadence', sa.String(length=20), nullable=True),
    sa.Column('gm_name', sa.String(length=255), nullable=True),
    sa.Column('gm_email', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('meetings',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('store_id', sa.Uuid(), nullable=False),
    sa.Column('meeting_date', sa.Date(), nullable=False),
    sa.Column('packet_generated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('packet_url', sa.String(length=500), nullable=True),
    sa.Column('flagged_items_url', sa.String(length=500), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'PROCESSING', 'COMPLETED', 'ERROR', name='meetingstatus'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_meetings_store_id', 'meetings', ['store_id'], unique=False)
    op.create_table('contracts_in_transit',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('meeting_id', sa.Uuid(), nullable=False),
    sa.Column('store_id', sa.Uuid(), nullable=False),
    sa.Column('deal_number', sa.String(length=50), nullable=False),
    sa.Column('customer_name', sa.String(length=255), nullable=True),
    sa.Column('sale_date', sa.Date(), nullable=False),
    sa.Column('days_in_transit', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('lender', sa.String(length=255), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['meeting_id'], ['meetings.id'], ),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_contracts_in_transit_meeting_id', 'contracts_in_transit', ['meeting_id'], unique=False)
    op.create_index('ix_contracts_in_transit_store_id', 'contracts_in_transit', ['store_id'], unique=False)
    op.create_table('fi_chargebacks',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('meeting_id', sa.Uuid(), nullable=False),
    sa.Column('store_id', sa.Uuid(), nullable=False),
    sa.Column('account_number', sa.String(length=20), nullable=False),
    sa.Column('account_description', sa.String(length=255), nullable=True),
    sa.Column('current_balance', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('over_90_balance', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['meeting_id'], ['meetings.id'], ),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_fi_chargebacks_meeting_id', 'fi_chargebacks', ['meeting_id'], unique=False)
    op.create_index('ix_fi_chargebacks_store_id', 'fi_chargebacks', ['store_id'], unique=False)
    op.create_table('flags',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('meeting_id', sa.Uuid(), nullable=False),
    sa.Column('store_id', sa.Uuid(), nullable=False),
    sa.Column('category', sa.Enum('INVENTORY', 'PARTS', 'FINANCIAL', 'OPERATIONS', name='flagcategory'), nullable=False),
    sa.Column('severity', sa.Enum('YELLOW', 'RED', name='flagseverity'), nullable=False),
    sa.Column('field_name', sa.String(length=255), nullable=False),
    sa.Column('field_value', sa.String(length=255), nullable=True),
    sa.Column('threshold', sa.String(length=255), nullable=True),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('OPEN', 'RESPONDED', 'ESCALATED', name='flagstatus'), nullable=False),
    sa.Column('response_text', sa.Text(), nullable=True),
    sa.Column('responded_by', sa.String(length=255), nullable=True),
    sa.Column('responded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['meeting_id'], ['meetings.id'], ),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_flags_meeting_id', 'flags', ['meeting_id'], unique=False)
    op.create_index('ix_flags_store_id', 'flags', ['store_id'], unique=False)
    op.create_table('floorplan_reconciliations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('meeting_id', sa.Uuid(), nullable=False),
    sa.Column('store_id', sa.Uuid(), nullable=False),
    sa.Column('reconciliation_type', sa.Enum('NEW_237', 'USED_240', name='reconciliationtype'), nullable=False),
    sa.Column('book_balance', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('floorplan_balance', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('variance', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('unit_count_book', sa.Integer(), nullable=True),
    sa.Column('unit_count_floorplan', sa.Integer(), nullable=True),
    sa.Column('unit_count_variance', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['meeting_id'], ['meetings.id'], ),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_floorplan_reconciliations_meeting_id', 'floorplan_reconciliations', ['meeting_id'], unique=False)
    op.create_index('ix_floorplan_reconciliations_store_id', 'floorplan_reconciliations', ['store_id'], unique=False)
    op.create_table('missing_titles',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('meeting_id', sa.Uuid(), nullable=False),
    sa.Column('store_id', sa.Uuid(), nullable=False),
    sa.Column('stock_number', sa.String(length=50), nullable=False),
    sa.Column('deal_number', sa.String(length=50), nullable=True),
    sa.Column('customer_name', sa.String(length=255), nullable=True),
    sa.Column('days_missing', sa.Integer(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['meeting_id'], ['meetings.id'], ),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_missing_titles_meeting_id', 'missing_titles', ['meeting_id'], unique=False)
    op.create_index('ix_missing_titles_store_id', 'missing_titles', ['store_id'], unique=False)
    op.create_table('new_vehicle_inventory',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('meeting_id', sa.Uuid(), nullable=False),
    sa.Column('store_id', sa.Uuid(), nullable=False),
    sa.Column('stock_number', sa.String(length=50), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('make', sa.String(length=50), nullable=False),
    sa.Column('model', sa.String(length=100), nullable=False),
    sa.Column('vin', sa.String(length=17), nullable=True),
    sa.Column('days_in_stock', sa.Integer(), nullable=False),
    sa.Column('floorplan_balance', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('book_value', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('schedule_237_balance', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('is_demo', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['meeting_id'], ['meetings.id'], ),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_new_vehicle_inventory_meeting_id', 'new_vehicle_inventory', ['meeting_id'], unique=False)
    op.create_index('ix_new_vehicle_inventory_store_id', 'new_vehicle_inventory', ['store_id'], unique=False)
    op.create_table('open_repair_orders',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('meeting_id', sa.Uuid(), nullable=False),
    sa.Column('store_id', sa.Uuid(), nullable=False),
    sa.Column('ro_number', sa.String(length=50), nullable=False),
    sa.Column('open_date', sa.Date(), nullable=False),
    sa.Column('days_open', sa.Integer(), nullable=False),
    sa.Column('customer_name', sa.String(length=255), nullable=True),
    sa.Column('service_type', sa.String(length=50), nullable=True),
    sa.Column('cp_invoice_date', sa.Date(), nullable=True),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['meeting_id'], ['meetings.id'], ),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_open_repair_orders_meeting_id', 'open_repair_orders', ['meeting_id'], unique=False)
    op.create_index('ix_open_repair_orders_store_id', 'open_repair_orders', ['store_id'], unique=False)
    op.create_table('parts_analysis',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('meeting_id', sa.Uuid(), nullable=False),
    sa.Column('store_id', sa.Uuid(), nullable=False),
    sa.Column('period_month', sa.Integer(), nullable=False),
    sa.Column('period_year', sa.Integer(), nullable=False),
    sa.Column('cost_of_sales', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('average_investment', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('true_turnover', sa.Numeric(precision=4, scale=2), nullable=True),
    sa.Column('months_no_sale', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('obsolete_value', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('stock_order_performance', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('outstanding_orders_value', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('processed_orders_value', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('receipts_value', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['meeting_id'], ['meetings.id'], ),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_parts_analysis_meeting_id', 'parts_analysis', ['meeting_id'], unique=False)
    op.create_index('ix_parts_analysis_store_id', 'parts_analysis', ['store_id'], unique=False)
    op.create_table('parts_inventory',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('meeting_id', sa.Uuid(), nullable=False),
    sa.Column('store_id', sa.Uuid(), nullable=False),
    sa.Column('category', sa.Enum('PARTS_242', 'TIRES_243', 'GAS_OIL_GREASE_244', name='partscategory'), nullable=False),
    sa.Column('gl_account', sa.String(length=20), nullable=False),
    sa.Column('total_value', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['meeting_id'], ['meetings.id'], ),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_parts_inventory_meeting_id', 'parts_inventory', ['meeting_id'], unique=False)
    op.create_index('ix_parts_inventory_store_id', 'parts_inventory', ['store_id'], unique=False)
    op.create_table('policy_adjustments',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('meeting_id', sa.Uuid(), nullable=False),
    sa.Column('store_id', sa.Uuid(), nullable=False),
    sa.Column('gl_account', sa.String(length=20), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('adjustment_date', sa.Date(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['meeting_id'], ['meetings.id'], ),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_policy_adjustments_meeting_id', 'policy_adjustments', ['meeting_id'], unique=False)
    op.create_index('ix_policy_adjustments_store_id', 'policy_adjustments', ['store_id'], unique=False)
    op.create_table('prepaids',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('meeting_id', sa.Uuid(), nullable=False),
    sa.Column('store_id', sa.Uuid(), nullable=False),
    sa.Column('gl_account', sa.String(length=20), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['meeting_id'], ['meetings.id'], ),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_prepaids_meeting_id', 'prepaids', ['meeting_id'], unique=False)
    op.create_index('ix_prepaids_store_id', 'prepaids', ['store_id'], unique=False)
    op.create_table('receivables',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('meeting_id', sa.Uuid(), nullable=False),
    sa.Column('store_id', sa.Uuid(), nullable=False),
    sa.Column('receivable_type', sa.Enum('PARTS_SERVICE_200', 'WHOLESALE_220', 'FACTORY_2612', name='receivabletype'), nullable=False),
    sa.Column('schedule_number', sa.String(length=20), nullable=False),
    sa.Column('current_balance', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('over_30', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('over_60', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('over_90', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('total_balance', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['meeting_id'], ['meetings.id'], ),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_receivables_meeting_id', 'receivables', ['meeting_id'], unique=False)
    op.create_index('ix_receivables_store_id', 'receivables', ['store_id'], unique=False)
    op.create_table('service_loaners',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('meeting_id', sa.Uuid(), nullable=False),
    sa.Column('store_id', sa.Uuid(), nullable=False),
    sa.Column('stock_number', sa.String(length=50), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('make', sa.String(length=50), nullable=False),
    sa.Column('model', sa.String(length=100), nullable=False),
    sa.Column('vin', sa.String(length=17), nullable=True),
    sa.Column('days_in_service', sa.Integer(), nullable=False),
    sa.Column('book_value', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('current_value', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('negative_equity', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['meeting_id'], ['meetings.id'], ),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_service_loaners_meeting_id', 'service_loaners', ['meeting_id'], unique=False)
    op.create_index('ix_service_loaners_store_id', 'service_loaners', ['store_id'], unique=False)
    op.create_table('slow_to_accounting',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('meeting_id', sa.Uuid(), nullable=False),
    sa.Column('store_id', sa.Uuid(), nullable=False),
    sa.Column('deal_number', sa.String(length=50), nullable=False),
    sa.Column('sale_date', sa.Date(), nullable=False),
    sa.Column('days_to_accounting', sa.Integer(), nullable=False),
    sa.Column('customer_name', sa.String(length=255), nullable=True),
    sa.Column('salesperson', sa.String(length=255), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['meeting_id'], ['meetings.id'], ),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_slow_to_accounting_meeting_id', 'slow_to_accounting', ['meeting_id'], unique=False)
    op.create_index('ix_slow_to_accounting_store_id', 'slow_to_accounting', ['store_id'], unique=False)
    op.create_table('used_vehicle_inventory',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('meeting_id', sa.Uuid(), nullable=False),
    sa.Column('store_id', sa.Uuid(), nullable=False),
    sa.Column('stock_number', sa.String(length=50), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('make', sa.String(length=50), nullable=False),
    sa.Column('model', sa.String(length=100), nullable=False),
    sa.Column('vin', sa.String(length=17), nullable=True),
    sa.Column('days_in_stock', sa.Integer(), nullable=False),
    sa.Column('book_value', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('market_value', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('floorplan_balance', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('acquisition_source', sa.String(length=50), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['meeting_id'], ['meetings.id'], ),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_used_vehicle_inventory_meeting_id', 'used_vehicle_inventory', ['meeting_id'], unique=False)
    op.create_index('ix_used_vehicle_inventory_store_id', 'used_vehicle_inventory', ['store_id'], unique=False)
    op.create_table('warranty_claims',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('meeting_id', sa.Uuid(), nullable=False),
    sa.Column('store_id', sa.Uuid(), nullable=False),
    sa.Column('claim_number', sa.String(length=50), nullable=False),
    sa.Column('claim_date', sa.Date(), nullable=True),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['meeting_id'], ['meetings.id'], ),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_warranty_claims_meeting_id', 'warranty_claims', ['meeting_id'], unique=False)
    op.create_index('ix_warranty_claims_store_id', 'warranty_claims', ['store_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_warranty_claims_store_id', table_name='warranty_claims')
    op.drop_index('ix_warranty_claims_meeting_id', table_name='warranty_claims')
    op.drop_table('warranty_claims')
    op.drop_index('ix_used_vehicle_inventory_store_id', table_name='used_vehicle_inventory')
    op.drop_index('ix_used_vehicle_inventory_meeting_id', table_name='used_vehicle_inventory')
    op.drop_table('used_vehicle_inventory')
    op.drop_index('ix_slow_to_accounting_store_id', table_name='slow_to_accounting')
    op.drop_index('ix_slow_to_accounting_meeting_id', table_name='slow_to_accounting')
    op.drop_table('slow_to_accounting')
    op.drop_index('ix_service_loaners_store_id', table_name='service_loaners')
    op.drop_index('ix_service_loaners_meeting_id', table_name='service_loaners')
    op.drop_table('service_loaners')
    op.drop_index('ix_receivables_store_id', table_name='receivables')
    op.drop_index('ix_receivables_meeting_id', table_name='receivables')
    op.drop_table('receivables')
    op.drop_index('ix_prepaids_store_id', table_name='prepaids')
    op.drop_index('ix_prepaids_meeting_id', table_name='prepaids')
    op.drop_table('prepaids')
    op.drop_index('ix_policy_adjustments_store_id', table_name='policy_adjustments')
    op.drop_index('ix_policy_adjustments_meeting_id', table_name='policy_adjustments')
    op.drop_table('policy_adjustments')
    op.drop_index('ix_parts_inventory_store_id', table_name='parts_inventory')
    op.drop_index('ix_parts_inventory_meeting_id', table_name='parts_inventory')
    op.drop_table('parts_inventory')
    op.drop_index('ix_parts_analysis_store_id', table_name='parts_analysis')
    op.drop_index('ix_parts_analysis_meeting_id', table_name='parts_analysis')
    op.drop_table('parts_analysis')
    op.drop_index('ix_open_repair_orders_store_id', table_name='open_repair_orders')
    op.drop_index('ix_open_repair_orders_meeting_id', table_name='open_repair_orders')
    op.drop_table('open_repair_orders')
    op.drop_index('ix_new_vehicle_inventory_store_id', table_name='new_vehicle_inventory')
    op.drop_index('ix_new_vehicle_inventory_meeting_id', table_name='new_vehicle_inventory')
    op.drop_table('new_vehicle_inventory')
    op.drop_index('ix_missing_titles_store_id', table_name='missing_titles')
    op.drop_index('ix_missing_titles_meeting_id', table_name='missing_titles')
    op.drop_table('missing_titles')
    op.drop_index('ix_floorplan_reconciliations_store_id', table_name='floorplan_reconciliations')
    op.drop_index('ix_floorplan_reconciliations_meeting_id', table_name='floorplan_reconciliations')
    op.drop_table('floorplan_reconciliations')
    op.drop_index('ix_flags_store_id', table_name='flags')
    op.drop_index('ix_flags_meeting_id', table_name='flags')
    op.drop_table('flags')
    op.drop_index('ix_fi_chargebacks_store_id', table_name='fi_chargebacks')
    op.drop_index('ix_fi_chargebacks_meeting_id', table_name='fi_chargebacks')
    op.drop_table('fi_chargebacks')
    op.drop_index('ix_contracts_in_transit_store_id', table_name='contracts_in_transit')
    op.drop_index('ix_contracts_in_transit_meeting_id', table_name='contracts_in_transit')
    op.drop_table('contracts_in_transit')
    op.drop_index('ix_meetings_store_id', table_name='meetings')
    op.drop_table('meetings')
    op.drop_table('stores')
    # ### end Alembic commands ###
